name: purplestarmd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
         style: normal

   - family: BebasNeue
     fonts:
       - asset: assets/fonts/BebasNeue-Regular.ttf
         style: normal

   - family: NanumMyeongjo
     fonts:
       - asset: assets/fonts/NanumMyeongjo-Regular.ttf
         style: normal

  assets:
    - assets/images/